spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/crypto_monitor
    username: crypto_sentinel
    password: p0stgr3s
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.springframework.data.elasticsearch.client.WIRE: TRACE # Para ver as queries no console
    org.springframework.web.reactive.function.client.WebClient: DEBUG # Para ver as chamadas da API

uri-properties:
  baseUrl: https://api.coingecko.com/api/v3
  CoinListUrl: /coins/list
  CoinMarketUrl: /coins/markets
